### PR TITLE
Do not force creation of a subsegment for tiles too small to be encrypted

### LINKED ISSUE #105: CENC Subsamples
The spec states
"A subsample SHALL be created for each tile."

This implies that if a previous subsample is present with no encrypted data, one has to start a new subsample. Is this the intended behaviour ? This is not really optimal since it enforces a first subsample with no encrypted data whenever we have unencrypted OBUs before tile data (eg, frame header or clear metadata.
Shouldn't we rather have a new subsample for a tile only if there is something encrypted before ?

### PR DESCRIPTION
**Pull request by cconcolato**
closes #105

### CODE REVIEW

**Comment by cconcolato** [comment]
FYI @jeanlf, @tinskip, @dwsinger, @jyavenard

**Comment by robUx4** [comment]
Does this mean _a subsample SHALL be created_ if there's not going to be an encrypted part ? Or can it be merged into other subsamples ?

**Comment by tomfinegan** [comment]
Text change LGTM

**Comment by cconcolato** [comment]
> Does this mean _a subsample SHALL be created_ if there's not going to be an encrypted part ? Or can it be merged into other subsamples ?

The latter.

**Pull request merged**
