### PR TITLE
Assert ids for version 1.2.0 and draft 1.3.0

### PR DESCRIPTION
**Pull request by podborski**
- ~~finish editing `index_120.bs`~~
- ~~generate new `v1.2.0.html`~~
- ~~delete `index_120.bs and other intermediate files`~~

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/171.html" title="Last updated on Dec 11, 2023, 4:43 PM UTC (2510697)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/171/014d8ea...2510697.html" title="Last updated on Dec 11, 2023, 4:43 PM UTC (2510697)">Diff</a>

### CODE REVIEW

**Comment by cconcolato** [comment]
We need to backport this change in the Bikeshed file https://github.com/AOMediaCodec/av1-isobmff/commit/7f97ee24eca8f92fcd88db4deb02266f973ef192

**Comment by podborski** [comment]
Hi @cconcolato can you take a look at the index_120.bs? We have some troubles with bikeshed as it generates non valid html. (I see missing closing tags etc.) We also tried to run on the old version of the bikeshed and it still generates more changes than expected to the output html.

**Comment by cconcolato** [comment]
Have a look at http://services.w3.org/htmldiff

**Comment by cconcolato** [comment]
1. Generate the HTML of 1.2 with unmodified Bikeshed file but with the latest Bikeshed software. Confirm that there is no meaningful difference
2. Add asserts to the 1.2 Bikeshed file (including unicity hacks), generate HTML
3. Update 1.3 Bikeshed to fix the unclosed assert and to guarantee unicity of assert ids

**Comment by podborski** [comment]
> 1. Generate the HTML of 1.2 with unmodified Bikeshed file but with the latest Bikeshed software. Confirm that there is no meaningful difference

[v120_main.html vs v120_init.html diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2FAOMediaCodec%2Fav1-isobmff%2Fassert_ids_120%2Fv120_main.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2FAOMediaCodec%2Fav1-isobmff%2Fassert_ids_120%2Fv120_init.html)

Looks like we only have to slightly edit the header.

> 2. Add asserts to the 1.2 Bikeshed file (including unicity hacks), generate HTML

[v120_init.html vs v1.2.0.html diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2FAOMediaCodec%2Fav1-isobmff%2Fassert_ids_120%2Fv120_init.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2FAOMediaCodec%2Fav1-isobmff%2Fassert_ids_120%2Fv1.2.0.html)

the diff tool shows 130 changes but all of them are due to inserted assert id's. (content remains the same).

**Comment by cconcolato** [comment]
@podborski fyi https://github.com/speced/bikeshed/issues/2686

**Comment by podborski** [comment]
I believe the diff tool has an issue with the above hidden span hack we use:
image
It shows that the fields are removed (left side of the figure) while the generated html (right side of the figure) still shows that the fields are there.

**Comment by cconcolato** [comment]
We noticed that spans are closed with a p. This should be fixed.

**Review by cconcolato — APPROVED** [review]
I verified the v1.2.0.html in this PR against the one currently published. No meaningful differences.
I verified the HTML generated online from the index.bs in this PR against the latest draft. No meaningful differences.
@podborski you can merge after removing the extra files (index120_init.bs, index_120.bs and v120_*.html).

**Review by ruegfo — APPROVED** [review]

**Comment by cconcolato** [comment]
@podborski can you clean the extra HTML AND Bikeshed files?

**Review by cconcolato — APPROVED** [review]

**Pull request merged**
