### PR TITLE
Clarify the `colr` box

### PR DESCRIPTION
**Pull request by wantehchang**
Fix https://github.com/AOMediaCodec/av1-isobmff/issues/126.

***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-isobmff/pull/167.html" title="Last updated on Apr 7, 2023, 10:36 PM UTC (397984b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/167/c870786...wantehchang:397984b.html" title="Last updated on Apr 7, 2023, 10:36 PM UTC (397984b)">Diff</a>

### CODE REVIEW

**Comment by cconcolato** [comment]
Comments:
* we should indicate why the information is "authoritative" (because of ISOBMFF)
* we note that for CMAF video tracks that are NALU-based, the `colr` box is mandatory but that there is no such provision in general for video tracks. We should add it to our CMAF section and request MPEG to consider requiring the box for non-NALU video tracks.

**Comment by cconcolato** [comment]
We think the change is not breaking any existing content:
* old files without colr, we are not saying anything new in this PR, files remain valid or invalid
* old files with colr and flag=1, the change is from SHALL to SHOULD, so the old compliant files remain compliant. Old invalid files (used for negative testing) become valid.
* old files with colr and flag=0, the old spec was silent about it. With this PR all files become valid but clarifying that container-level information overrides stream-level information.

**Comment by cconcolato** [comment]
We could improve by saying:
* when SH does not have any 2, then we should NOT override the values but when a 2 value is used, then MAY/SHOULD be overriden.

**Comment by podborski** [comment]
After syncing with our guys on this. SH and colr SHALL match if SH is not signaling unspecified values. For any 2 (unspecified in SH) we agree with Cyril, the container level signaling could specify what it is. We also need to highlight in the AV1 ISOBMFF spec the sentence from ISOBMFF spec which says that container level over-rides the information in the bitstream.

In addition to that full range signaling SHALL match whatever is in the bitstream.

**Comment by wantehchang** [comment]
Dimitri: Just wanted to confirm I understood your comment correctly. You don't want the colr box to contradict any specified value (i.e., != 2) in the AV1 sequence header OBU, even though ISOBMFF allows that. Is this correct?

**Comment by podborski** [comment]
> Dimitri: Just wanted to confirm I understood your comment correctly. You don't want the colr box to contradict any specified value (i.e., != 2) in the AV1 sequence header OBU, even though ISOBMFF allows that. Is this correct?

Correct.

**Comment by cconcolato** [comment]
The sentence in ISOBMFF indicating that the container level information has precedence is in section 12.1.5.1 "Colour information Definition" of the 7th edition:
> If colour information is supplied in both this box, and also in the video bitstream, this box takes precedence, and over-rides the information in the bitstream.

We should simply rephrase it and point to the "Colour Information" box definition (rather than to a specific section, as this might change in future versions)

**Comment by wantehchang** [comment]
@cconcolato @podborski I made the changes as you suggested. Please review the new version of this PR. Thanks.

**Review by cconcolato — APPROVED** [review]

**Pull request merged**
