### PR TITLE
Initial presentation delay updates.

### PR DESCRIPTION
**Pull request by tomfinegan**
A couple small changes:
1) initial_display_delay_minus_1 in the latest buffer model proposal is 4 bits.
I've updated the field in the sample entry to use 4 bits.
2) Add initial_presentation_delay_present flag.

### CODE REVIEW

**Comment by rbouqueau** [comment]
@cconcolato Could you keep us updated about this when you know? The GPAC default value for this is still 8.

**Comment by tomfinegan** [comment]
> initial_display_delay_minus_1 in the latest buffer model proposal is 4 bits.
> I've updated the field in the sample entry to use 4 bits.

Actually in the spec this is currently 4 bits. Note that per implementation the max value is 10.

> Add initial_presentation_delay_present flag.

In the current version of the spec this maps to display_model_param_present_flag.

**Comment by cconcolato** [comment]
LGTM, maybe the following text should be updated:
> When smooth presentation can be guaranteed after decoding the first sample, the value 0 SHALL be used. If an ISOBMFF writer cannot verify the above procedure, initial_presentation_delay SHOULD be set to its maximum value *or initial_presentation_delay_present SHOULD be set to 0*.

**Comment by tomfinegan** [comment]
Ah, yes. Done. PTAL/Thanks!

> LGTM, maybe the following text should be updated:

>> When smooth presentation can be guaranteed after decoding the first sample, the value 0
 >> SHALL be used. If an ISOBMFF writer cannot verify the above procedure, 
>> initial_presentation_delay SHOULD be set to its maximum value or 
>> initial_presentation_delay_present SHOULD be set to 0.

**Pull request merged**
