### PR TITLE
Fix bibliographical references

### PR DESCRIPTION
**Pull request by tobie**
***

### :boom: Error: 400 Bad Request :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 23, 2019, 8:01 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Ftobie%2Fav1-isobmff%2F6a70b26e0ca5c47eef13bfa0f1540b749bf23884%2Findex.bs&md-warning=not%20ready)

```
Error running preprocessor, returned code: 1.
FATAL ERROR: Couldn't find 'CMAF' in bibliography data. Did you mean:
  mpegcmaf
  hmac
  foaf
  voaf
  coap
  cuap
 ✘  Did not generate, due to fatal errors
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20AOMediaCodec/av1-isobmff%23113.)._
</details>

### CODE REVIEW

**Comment by plinss** [comment]
The bikeshed service updates its data sources whenever the spec database changes. That happens within minutes after a CSSWG spec update, but it also scans all tracked specs everyday just after midnight (pacific time), so long as one of those specs has been updated bikeshed will pull new data.

There's also a webhook to update the bikeshed code whenever it gets updated. It would be trivial to add a webhook for the specref repo to cause an update.

**Comment by tobie** [comment]
> There's also a webhook to update the bikeshed code whenever it gets updated. It would be trivial to add a webhook for the specref repo to cause an update.

We should totally do that. Do you need anything from me?

**Comment by tobie** [comment]
So this one is good to merge, despite the PR-Preview error. The error exists because PR-Preview is attempting to run the build for the current gh-pages branch tip (for the HTML diff) and fails because the tip has these biblio issues.

**Comment by cconcolato** [comment]
Closing as the problem was solved with #114

**Pull request closed without merging**
